### ISSUE TITLE
Invalid colon

### ISSUE THREAD

**Issue by tanrax** [juusaw/amp-jekyll#21]
ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    The URL /:title/ is invalid because it contains a colon.

**Comment by juusaw** [comment]
Hi!

I haven't seen an error like that before. It looks like the `:title` symbol is being interpreted literally. Are you sure this bug is caused by amp-jekyll? If so, could you add some more information on your setup, like Jekyll version and `_config.yml` keys related to the plugin?

**Comment by tanrax** [comment]
Yes, it happens to me with amp-jekyll hehe. My _config.yml where it fails

```
defaults:
  -
    scope:
      path: '_posts'
    values:
      layout: items/blog-single
      permalink: /:title/
      status: publish
      published: true
  -
```
